# Generated by Django 3.2 on 2021-04-30 02:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0003_auto_20210430_0819'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовка')),
                ('body', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='dashboard/products/', verbose_name='Изброжения')),
                ('first_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='От')),
                ('last_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='До')),
                ('isbn_code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Коды товара(ISBN, UPC, GTIN)')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата выхода')),
                ('view', models.IntegerField(default=0, verbose_name='Просмотров')),
                ('laptop_class', models.CharField(blank=True, max_length=64, null=True, verbose_name='Класс ноутбука')),
                ('series', models.CharField(blank=True, max_length=64, null=True, verbose_name='Серия')),
                ('processor_clock_speed', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Тактовая частота процессора Turbo Boost, ГГц')),
                ('processor_series', models.CharField(max_length=64, verbose_name='Серия процессора')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dashboard.category', verbose_name='Категория')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Ноутбук',
                'verbose_name_plural': 'Ноутбуки',
            },
        ),
        migrations.CreateModel(
            name='Fridge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовка')),
                ('body', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='dashboard/products/', verbose_name='Изброжения')),
                ('first_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='От')),
                ('last_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='До')),
                ('isbn_code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Коды товара(ISBN, UPC, GTIN)')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата выхода')),
                ('view', models.IntegerField(default=0, verbose_name='Просмотров')),
                ('useful_total_volume', models.PositiveIntegerField(blank=True, null=True, verbose_name='Полезный общий объем, л')),
                ('open_door_signal', models.BooleanField(default=False, verbose_name='Сигнал открытой двери')),
                ('freezer_defrost_system', models.CharField(blank=True, max_length=64, null=True, verbose_name='Система размораживания морозильной камеры')),
                ('number_of_sections', models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество секций')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dashboard.category', verbose_name='Категория')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Холодильник',
                'verbose_name_plural': 'Холодильники',
            },
        ),
    ]
