# Generated by Django 3.2 on 2021-04-30 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0004_alter_dashboard_branch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sneakers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовка')),
                ('body', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='dashboard/products/', verbose_name='Изброжения')),
                ('first_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='От')),
                ('last_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='До')),
                ('isbn_code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Коды товара(ISBN, UPC, GTIN)')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата выхода')),
                ('view', models.IntegerField(default=0, verbose_name='Просмотров')),
                ('upper_material', models.CharField(blank=True, max_length=64, null=True, verbose_name='Материал верха')),
                ('internal_material', models.CharField(blank=True, max_length=64, null=True, verbose_name='Внутренний материал')),
                ('sole_material', models.CharField(blank=True, max_length=64, null=True, verbose_name='Материал подошвы')),
                ('season', models.CharField(blank=True, max_length=64, null=True, verbose_name='Сезон')),
                ('color', models.CharField(blank=True, max_length=64, null=True, verbose_name='Цвет')),
                ('sport_type', models.CharField(blank=True, max_length=64, null=True, verbose_name='Вид спорта')),
                ('country_of_manufacture', models.CharField(blank=True, max_length=64, null=True, verbose_name='Страна производства')),
                ('zip_closure', models.CharField(blank=True, max_length=64, null=True, verbose_name='Застежка')),
                ('article_number', models.CharField(blank=True, max_length=64, null=True, verbose_name='Артикул')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dashboard.category', verbose_name='Категория')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Кроссовка',
                'verbose_name_plural': 'Кроссовки',
            },
        ),
    ]
