# Generated by Django 3.2 on 2021-08-02 16:07

import dashboard.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Ключовой адрес')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Тема')),
                ('body', models.TextField(verbose_name='Описание')),
                ('date_send', models.DateTimeField(auto_now_add=True, verbose_name='Дата отправление')),
                ('checked', models.BooleanField(default=False, verbose_name='Проверка')),
                ('from_send', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Кому')),
                ('to_send', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='send_to', to=settings.AUTH_USER_MODEL, verbose_name='От кого')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомлений',
                'ordering': ['-date_send'],
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
            ],
            options={
                'verbose_name': 'Подкатегория',
                'verbose_name_plural': 'Подкатегорий',
                'ordering': ('super_category__name', 'name'),
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('dashboard.category',),
        ),
        migrations.CreateModel(
            name='SuperCategory',
            fields=[
            ],
            options={
                'verbose_name': 'Надкатегория',
                'verbose_name_plural': 'Надкатегорий',
                'ordering': ('name',),
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('dashboard.category',),
        ),
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logotype', models.ImageField(blank=True, help_text='Максимальный размер файла 2MB', null=True, upload_to='dashboard/avatar/', validators=[dashboard.models.Dashboard.validate_logotype], verbose_name='Логотип')),
                ('body', models.TextField(blank=True, max_length=300, null=True, verbose_name='О вас')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ваше имя')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ваше фамилия')),
                ('gender', models.CharField(choices=[('NOT_DEFINED', 'Не указано'), ('MALE', 'Мужской'), ('FAMALE', 'Женский')], default='Не указано', max_length=12, verbose_name='Пол')),
                ('address', models.TextField(blank=True, max_length=255, null=True, verbose_name='Адрес')),
                ('phone', phone_field.models.PhoneField(blank=True, help_text='Контакт телефона', max_length=31, verbose_name='Телефон')),
                ('city', models.CharField(choices=[('ALMATY', 'Алматы'), ('NURSULTAN', 'Нұр-Сұлтан'), ('SHYMKENT', 'Шымкент'), ('AQTOBE', 'Ақтөбе'), ('QARAGANDY', 'Қарағанды'), ('TARAZ', 'Тараз'), ('PAVLODAR', 'Павлодар'), ('OSKEMEN', 'Өскемен'), ('SEMEI', 'Семей'), ('ATYRAU', 'Атырау'), ('QOSTANAI', 'Қостанай'), ('QYZYLORDA', 'Қызылорда'), ('ORAL', 'Орал'), ('PETROPAVL', 'Петропавл'), ('AQTAU', 'Ақтау'), ('TEMYRTAU', 'Теміртау'), ('KOKSHETAU', 'Көкшетау'), ('TALDYQORGAN', 'Талдықорған'), ('EKYBASTUZ', 'Екібастұз'), ('RUDNY', 'Рудный'), ('ZHANAOZEN', 'Жаңаөзен'), ('BALQASH', 'Балқаш'), ('KENTAU', 'Кентау'), ('QASKELEN', 'Қаскелең'), ('SATBAEV', 'Сәтбаев'), ('QULSARY', 'Құлсары')], default='ALMATY', max_length=255, verbose_name='Город')),
                ('reserve_email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Резервный email')),
                ('website', models.CharField(blank=True, max_length=255, null=True, verbose_name='Веб сайт')),
                ('branding', models.BooleanField(default=False, verbose_name='Брендинг')),
                ('for_clients', models.BooleanField(default=False, verbose_name='Вы открываете это для клиента?')),
                ('brand', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Бренд')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dashboard.supercategory', verbose_name='Отрасль')),
            ],
            options={
                'verbose_name': 'Панель управление',
                'verbose_name_plural': 'Панели управление',
            },
        ),
        migrations.AddField(
            model_name='category',
            name='super_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dashboard.supercategory', verbose_name='Надкатегория'),
        ),
    ]
