# Generated by Django 3.2 on 2021-07-24 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='checked',
            field=models.BooleanField(default=False, verbose_name='Проверка'),
        ),
    ]
