# Generated by Django 3.2 on 2021-04-30 01:05

import dashboard.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255, verbose_name='Название категорий')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Ключовой адрес')),
                ('image', models.ImageField(blank=True, null=True, upload_to='dashboard/categories/', verbose_name='Изброжение')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категорий',
            },
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='logotype',
            field=models.ImageField(blank=True, help_text='Максимальный размер файла 2MB', null=True, upload_to='dashboard/avatar/', validators=[dashboard.models.Dashboard.validate_logotype], verbose_name='Логотип'),
        ),
        migrations.CreateModel(
            name='Smartphone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовка')),
                ('body', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='dashboard/products/', verbose_name='Изброжения')),
                ('first_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='От')),
                ('last_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='До')),
                ('isbn_code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Коды товара(ISBN, UPC, GTIN)')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата выхода')),
                ('view', models.IntegerField(default=0, verbose_name='Просмотров')),
                ('proccessor', models.CharField(max_length=255)),
                ('ram', models.CharField(max_length=255)),
                ('camera', models.CharField(max_length=255)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dashboard.category', verbose_name='Категория')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cleaner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовка')),
                ('body', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='dashboard/products/', verbose_name='Изброжения')),
                ('first_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='От')),
                ('last_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='До')),
                ('isbn_code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Коды товара(ISBN, UPC, GTIN)')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата выхода')),
                ('view', models.IntegerField(default=0, verbose_name='Просмотров')),
                ('acumilator', models.CharField(max_length=255)),
                ('cube', models.CharField(max_length=255)),
                ('vat', models.CharField(max_length=255)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dashboard.category', verbose_name='Категория')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
