# Generated by Django 3.2 on 2021-07-03 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_category_image'),
        ('dashboard', '0002_alter_dashboard_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='address',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.category', verbose_name='Отрасль'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='gender',
            field=models.CharField(choices=[('NOT_DEFINED', 'Не указано'), ('MALE', 'Мужской'), ('FAMALE', 'Женский')], default='Не указано', max_length=12, verbose_name='Пол'),
        ),
    ]
