# Generated by Django 3.2 on 2021-08-26 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='city',
            field=models.CharField(choices=[('ALMATY', 'Алматы'), ('NURSULTAN', 'Нұр-Сұлтан'), ('SHYMKENT', 'Шымкент'), ('AQTOBE', 'Ақтөбе'), ('QARAGANDY', 'Қарағанды'), ('TARAZ', 'Тараз'), ('PAVLODAR', 'Павлодар'), ('OSKEMEN', 'Өскемен'), ('SEMEI', 'Семей'), ('ATYRAU', 'Атырау'), ('QOSTANAI', 'Қостанай'), ('QYZYLORDA', 'Қызылорда'), ('ORAL', 'Орал'), ('PETROPAVL', 'Петропавл'), ('AQTAU', 'Ақтау'), ('TEMYRTAU', 'Теміртау'), ('KOKSHETAU', 'Көкшетау'), ('TALDYQORGAN', 'Талдықорған'), ('EKYBASTUZ', 'Екібастұз'), ('RUDNY', 'Рудный'), ('ZHANAOZEN', 'Жаңаөзен'), ('BALQASH', 'Балқаш'), ('KENTAU', 'Кентау'), ('QASKELEN', 'Қаскелең'), ('SATBAEV', 'Сәтбаев'), ('QULSARY', 'Құлсары')], default='ALMATY', max_length=64, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='first_name',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Ваше имя'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='last_name',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Ваше фамилия'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='reserve_email',
            field=models.EmailField(blank=True, max_length=64, null=True, verbose_name='Резервный email'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='website',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Веб сайт'),
        ),
    ]
