# Generated by Django 3.2 on 2021-04-30 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20210430_0705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smartphone',
            name='category',
        ),
        migrations.RemoveField(
            model_name='smartphone',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Cleaner',
        ),
        migrations.DeleteModel(
            name='Smartphone',
        ),
    ]
