# Generated by Django 3.2 on 2021-04-30 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20210430_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='branch',
            field=models.CharField(choices=[('CLOTHES', 'Одежда'), ('VIRTUAL_SERVICES', 'Виртуальные сервисы'), ('BEAUTY', 'Красота'), ('ELECTRONICS', 'Электроника'), ('FURNIURE', 'Мебель'), ('CRAFTS', 'Ремесла'), ('JEWERLY', 'Ювелирные украшения'), ('PICTURE', 'Картина'), ('PHOTO', 'Фотография'), ('RESTAURANTS', 'Рестораны'), ('FOOD_PRODUCTS', 'Продовольственные товары'), ('OTHER_FOOD_AND_DRINKS', 'Другая еда и напитки'), ('SPORTING', 'Спортивный'), ('TOYS', 'Игрушки'), ('SERVICES', 'Услуги'), ('ANOTHER', 'Другой'), ('NOT_SELECTED', 'Не выбран')], default='NOT_SELECTED', max_length=50, verbose_name='Отрасль'),
        ),
    ]
