# Generated by Django 3.2 on 2021-09-15 09:59

import dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboard',
            name='city',
        ),
        migrations.RemoveField(
            model_name='dashboard',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='dashboard',
            name='last_name',
        ),
        migrations.AddField(
            model_name='author',
            name='picture',
            field=models.ImageField(blank=True, help_text='Максимальный размер файла 2MB', null=True, upload_to='dashboard/authors/', validators=[dashboard.models.Author.validate_picture]),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='full_name',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Ваше полная имя'),
        ),
    ]
