# Generated by Django 3.2 on 2021-07-10 03:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0004_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='from_to',
            new_name='from_send',
        ),
        migrations.AddField(
            model_name='notification',
            name='to_send',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='send_to', to='accounts.brand', verbose_name='Владелец'),
            preserve_default=False,
        ),
    ]
