# Generated by Django 3.2 on 2021-05-10 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20210509_1645'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OverviewProduct',
        ),
    ]
