# Generated by Django 3.2 on 2021-05-10 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_overviewproducts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OverviewProducts',
        ),
    ]
