# Generated by Django 4.1.1 on 2022-09-10 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='membership_type',
            field=models.CharField(choices=[('FREE', 'Free'), ('PREMIUM', 'Premium'), ('PREMIUM_FOR_DUO', 'Premium for duo'), ('PREMIUM_FOR_GROUP', 'Premium for group'), ('PREMIUM_FOR_STUDENTS', 'Premium for students')], default='Free', max_length=60, verbose_name='Membership type'),
        ),
    ]
