# Generated by Django 3.2 on 2021-10-25 04:56

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=phone_field.models.PhoneField(help_text='Контакт телефона', max_length=31, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_name',
            field=models.CharField(max_length=64, verbose_name='Полная имя'),
        ),
    ]
