# Generated by Django 3.2 on 2021-08-26 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='brandname',
            field=models.CharField(max_length=32, unique=True, verbose_name='Имя бренда'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='email',
            field=models.EmailField(max_length=64, unique=True, verbose_name='адрес электронной почты'),
        ),
    ]
