# Generated by Django 4.1.1 on 2022-09-10 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_membership_membership_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='branding',
            field=models.BooleanField(default=False, verbose_name='Branding'),
        ),
    ]
