# Generated by Django 3.2 on 2021-08-28 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_favorite_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
