# Generated by Django 3.2 on 2021-05-16 06:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255, verbose_name='Название категорий')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Ключовой адрес')),
                ('image', models.ImageField(blank=True, null=True, upload_to='dashboard/categories/', verbose_name='Изброжение')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категорий',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовка')),
                ('body', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='dashboard/products/', verbose_name='Изброжения')),
                ('first_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='От')),
                ('last_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='До')),
                ('isbn_code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Коды товара(ISBN, UPC, GTIN)')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата выхода')),
                ('view', models.IntegerField(default=0, verbose_name='Просмотров')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'ordering': ('-timestamp',),
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=200, verbose_name='Сообщение')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expiration_date', models.DateTimeField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Активность',
                'verbose_name_plural': 'Активности',
            },
        ),
    ]
