# Generated by Django 3.2 on 2021-10-23 08:56

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profile', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album', models.ImageField(blank=True, null=True, upload_to='profile/chapters/', verbose_name='Альбом')),
                ('name', models.CharField(max_length=64, verbose_name='Название')),
                ('about', models.TextField(max_length=300, verbose_name='Кратко о разделе')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата выхода')),
            ],
            options={
                'verbose_name': 'Раздел',
                'verbose_name_plural': 'Разделы',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Videohosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Название')),
                ('body', models.TextField(blank=True, verbose_name='Описание')),
                ('frame_url', models.CharField(max_length=255, verbose_name='Ссылка')),
                ('access', models.BooleanField(default=True, verbose_name='Доступ к видео')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата выхода')),
                ('view', models.IntegerField(default=0, verbose_name='Просмотров')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.chapter', verbose_name='Раздел')),
            ],
            options={
                'verbose_name': 'Видеохостинг',
                'verbose_name_plural': 'Видеохостинг',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='Заголовка')),
                ('brand', models.CharField(max_length=32, verbose_name='Бренд')),
                ('about', models.TextField(blank=True, max_length=300, null=True, verbose_name='Кратко о продукте')),
                ('body', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание')),
                ('album', models.ImageField(blank=True, null=True, upload_to='profile/products/', verbose_name='Альбом')),
                ('isbn_code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Коды товара(ISBN, UPC, GTIN)')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата выхода')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
                ('production', models.BooleanField(default=False, verbose_name='Публикация')),
                ('authors', models.ManyToManyField(related_name='authors', to=settings.AUTH_USER_MODEL, verbose_name='Авторы')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile.supercategory', verbose_name='Категория')),
                ('favorites', models.ManyToManyField(blank=True, related_name='favorites', to=settings.AUTH_USER_MODEL, verbose_name='Избранные')),
                ('observers', models.ManyToManyField(blank=True, related_name='observers', to=settings.AUTH_USER_MODEL, verbose_name='Подписчики')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategory', to='profile.subcategory', verbose_name='Подкатегория')),
            ],
            options={
                'verbose_name': 'Релиз',
                'verbose_name_plural': 'Релизы',
                'ordering': ('-timestamp',),
            },
        ),
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=64, verbose_name='Названия')),
                ('value', models.CharField(blank=True, max_length=64, null=True, verbose_name='Значение')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='profile.supercategory', verbose_name='Категория')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Релиз')),
            ],
            options={
                'verbose_name': 'Xарактеристика',
                'verbose_name_plural': 'Xарактеристики',
            },
        ),
        migrations.AddField(
            model_name='chapter',
            name='release',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Релиз'),
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=200, verbose_name='Сообщение')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expiration_date', models.DateTimeField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Активность',
                'verbose_name_plural': 'Активности',
            },
        ),
    ]
