# Generated by Django 3.2 on 2021-07-28 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videohosting',
            name='body',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.DeleteModel(
            name='Multilink',
        ),
    ]
