# Generated by Django 3.2 on 2021-08-05 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Docs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовка')),
                ('body', models.TextField(blank=True, verbose_name='Описание')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата выхода')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновление')),
                ('videohosting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.videohosting', verbose_name='Видеохостинг')),
            ],
            options={
                'verbose_name': 'Документация',
                'verbose_name_plural': 'Документации',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=300, verbose_name='Тело комментарий')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата написание')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('videohosting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.videohosting', verbose_name='Видеохостинг')),
            ],
            options={
                'verbose_name': 'Комментарии',
                'verbose_name_plural': 'Комментарии',
            },
        ),
    ]
