# Generated by Django 3.2 on 2021-10-23 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videohosting',
            name='chapter',
        ),
        migrations.AddField(
            model_name='videohosting',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Релиз'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Chapter',
        ),
    ]
