# Generated by Django 3.2 on 2021-08-08 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210807_1328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='view',
        ),
        migrations.AddField(
            model_name='videohosting',
            name='view',
            field=models.IntegerField(default=0, verbose_name='Просмотров'),
        ),
        migrations.AlterField(
            model_name='videohosting',
            name='title',
            field=models.CharField(max_length=32, verbose_name='Название'),
        ),
    ]
