# Generated by Django 3.2 on 2021-08-05 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_docs'),
    ]

    operations = [
        migrations.AddField(
            model_name='docs',
            name='videohosting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.videohosting', verbose_name='Видеохостинг'),
        ),
    ]
