# Generated by Django 3.2 on 2021-07-28 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        ('products', '0002_auto_20210728_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subcategory', to='dashboard.subcategory', verbose_name='Подкатегория'),
            preserve_default=False,
        ),
    ]
