# Generated by Django 3.2 on 2021-08-26 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210808_1300'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videohosting',
            options={'ordering': ['title'], 'verbose_name': 'Видеохостинг', 'verbose_name_plural': 'Видеохостинг'},
        ),
    ]
