# Generated by Django 3.2 on 2021-05-16 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='features',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='products.category', verbose_name='Категория'),
            preserve_default=False,
        ),
    ]
