# Generated by Django 3.2 on 2022-01-02 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_chapter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videohosting',
            name='product',
        ),
        migrations.AddField(
            model_name='videohosting',
            name='chapter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.chapter', verbose_name='Раздел'),
            preserve_default=False,
        ),
    ]
