# Generated by Django 3.2 on 2021-08-05 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_docs_videohosting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docs',
            name='body',
        ),
    ]
