# Generated by Django 3.2 on 2021-08-26 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_videohosting_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=40, verbose_name='Заголовка'),
        ),
        migrations.AlterField(
            model_name='videohosting',
            name='title',
            field=models.CharField(max_length=64, verbose_name='Название'),
        ),
    ]
