# Generated by Django 3.2 on 2021-08-05 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_docs_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='docs',
            name='body',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
    ]
