# Generated by Django 3.2 on 2022-01-02 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20220102_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='videohosting',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Релиз'),
            preserve_default=False,
        ),
    ]
