# Generated by Django 3.2 on 2022-01-03 15:11

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_videohosting_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='videohosting',
            name='s_body',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
