# Generated by Django 3.2 on 2021-08-28 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20210828_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='about',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='Кратко о продукте'),
        ),
    ]
