# Generated by Django 3.2 on 2022-01-03 15:15

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_videohosting_s_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videohosting',
            name='s_body',
        ),
        migrations.AlterField(
            model_name='videohosting',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
