# Generated by Django 3.2 on 2021-08-29 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_favorites'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videohosting',
            options={'ordering': ['timestamp'], 'verbose_name': 'Видеохостинг', 'verbose_name_plural': 'Видеохостинг'},
        ),
    ]
