# Generated by Django 3.2 on 2021-09-15 10:17

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20210915_1559'),
        ('products', '0010_product_authors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='authors',
            field=models.ManyToManyField(related_name='authors', to='dashboard.Author', verbose_name='Авторы'),
        ),
        migrations.AlterField(
            model_name='product',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
