# Generated by Django 3.2 on 2021-10-03 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20210915_1617'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название')),
                ('about', models.TextField(max_length=300, verbose_name='Кратко о разделе')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата выхода')),
            ],
            options={
                'verbose_name': 'Раздел',
                'verbose_name_plural': 'Разделы',
                'ordering': ['timestamp'],
            },
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
