# Generated by Django 3.2 on 2021-10-03 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20211003_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='album',
            field=models.ImageField(blank=True, null=True, upload_to='dashboard/chapters/', verbose_name='Альбом'),
        ),
    ]
